typedef enum {SUCCESS = 0, FAILURE, ERROR_SIZE, PARAM_ERROR, ERROR_EXTRACT, ERROR_EMBED, ERROR_SPLIT, ERROR_DECRYPTION, ERROR_ENCRYPTION, ERROR_BMP_TO_MATRIX, ERROR_GET_FILE_INFO, ERROR_CONCATENATE } ret_value;

#define ERROR_MEMORY_ALLOCATION -1
